# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Confuse_config = debug
  Sandbox_config = debug
endif
ifeq ($(config),release)
  Confuse_config = release
  Sandbox_config = release
endif
ifeq ($(config),dist)
  Confuse_config = dist
  Sandbox_config = dist
endif

PROJECTS := Confuse Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Confuse:
ifneq (,$(Confuse_config))
	@echo "==== Building Confuse ($(Confuse_config)) ===="
	@${MAKE} --no-print-directory -C Confuse -f Makefile config=$(Confuse_config)
endif

Sandbox: Confuse
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Confuse -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Confuse"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"